const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname, DB=path.join(ROOT,'data','products.json'), PORT=process.env.PORT||3000, ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'change-me';
let products=JSON.parse(fs.readFileSync(DB,'utf8')); products=products.map((x,i)=>({...x,id:x.id||String(i+1),active:x.active!==false}));
let sessions=new Set(); function persist(){fs.writeFileSync(DB,JSON.stringify(products,null,2),'utf8')} function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(obj))} function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})} function auth(req){let h=req.headers.authorization||'';return h.startsWith('Bearer ')&&sessions.has(h.slice(7))}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://localhost');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(u.pathname==='/api/login'&&req.method==='POST'){let b=await body(req);if(b.password!==ADMIN_PASSWORD)return json(res,401,{error:'รหัสผ่านไม่ถูกต้อง'});let t=crypto.randomBytes(24).toString('hex');sessions.add(t);return json(res,200,{token:t})}
if(u.pathname==='/api/products'&&req.method==='GET'){let all=u.searchParams.get('all')==='1';if(all&&!auth(req))return json(res,401,{error:'Unauthorized'});return json(res,200,all?products:products.filter(x=>x.active!==false))}
if(u.pathname==='/api/products'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'Unauthorized'});let b=await body(req);b.id=String(Date.now());b.active=true;products.push(b);persist();return json(res,201,b)}
if(u.pathname==='/api/products'&&req.method==='PUT'){if(!auth(req))return json(res,401,{error:'Unauthorized'});let b=await body(req),i=products.findIndex(x=>x.id===String(b.id));if(i<0)return json(res,404,{error:'Not found'});products[i]={...products[i],...b,id:String(b.id)};persist();return json(res,200,products[i])}
let m=u.pathname.match(/^\/api\/products\/([^/]+)$/);if(m&&req.method==='PATCH'){if(!auth(req))return json(res,401,{error:'Unauthorized'});let i=products.findIndex(x=>x.id===m[1]);if(i<0)return json(res,404,{error:'Not found'});let b=await body(req);products[i]={...products[i],...b};persist();return json(res,200,products[i])}
let file=u.pathname==='/'?'/index.html':u.pathname;if(file==='/admin')file='/admin.html';let fp=path.join(ROOT,'public',file);if(!fp.startsWith(path.join(ROOT,'public')))return json(res,403,{error:'Forbidden'});if(fs.existsSync(fp)){let ext=path.extname(fp),ct={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[ext]||'text/plain';res.writeHead(200,{'Content-Type':ct});return res.end(fs.readFileSync(fp))}json(res,404,{error:'Not found'})}catch(e){console.error(e);json(res,500,{error:e.message})}});server.listen(PORT,()=>console.log(`ABB Breaker Selector running on http://localhost:${PORT}`));
